language: go
go:
  - "1.12.7"

sudo: false

env:
  - GO111MODULE=on

before_install:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - export PATH=$PATH:$HOME/gopath/bin
  - travis_wait 30 ./goclean.sh
